version: "v2.21.0"

services:
  case-lab-db:
    image: postgres:14-alpine
    container_name: case-lab-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - case-lab
    healthcheck:
      test: [ "CMD", "pg_isready","-d","postgres","-U","postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/lib/postgresql/data

  case-lab-java-discovery-service:
    image: case-lab-java-discovery-service
    build:
      dockerfile: Dockerfile
      context: Discovery-Service
    restart: always
    container_name: case-lab-java-discovery-service
    networks:
      - case-lab
    ports:
      - "8761:8761"
    depends_on:
      case-lab-db:
        condition: service_healthy
      minio:
        condition: service_started

  case-lab-java-client-self-service:
    image: case-lab-java-client-self-service
    build:
      dockerfile: Dockerfile
      context: Client-Self-Service
    restart: always
    container_name: case-lab-java-client-self-service
    networks:
      - case-lab
    ports:
      - "8081:8081"
    environment:
      JWT_TECHNICAL_USER: ${JWT_TECHNICAL_USER}
      CLIENT_REFRESH_TOKEN: ${CLIENT_REFRESH_TOKEN}
      CLIENT_ACCESS_TOKEN: ${CLIENT_ACCESS_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      case-lab-java-discovery-service:
        condition: service_started
      case-lab-db:
        condition: service_healthy
      minio:
        condition: service_started

  case-lab-java-crm:
    image: case-lab-java-crm
    build:
      dockerfile: Dockerfile
      context: CRM
    restart: always
    container_name: case-lab-java-crm
    environment:
      MINIO_ACCESS: ${MINIO_ACCESS}
      MINIO_SECRET: ${MINIO_SECRET}
      MINIO_URL: ${MINIO_URL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
    networks:
      - case-lab
    ports:
      - "8080:8080"
    depends_on:
      case-lab-java-discovery-service:
        condition: service_started
      case-lab-db:
        condition: service_healthy
      minio:
        condition: service_started

  minio:
    image: minio/minio:latest
    command: server --console-address ":9090" /data/
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
    volumes:
      - ~/minio/data:/data
    networks:
      case-lab:

volumes:
  minio-storage:

networks:
  case-lab:
    driver: bridge



