spring:
  application:
    name: client-self-service
  data:
    redis:
      host: 5.35.83.19
      password: ${REDIS_PASSWORD}
      port: 6379
server:
  port: 8081
redis_host_name: redis
redis_password: ${REDIS_PASSWORD}
redis_username: ${REDIS_USERNAME}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
client_access_token: ${CLIENT_ACCESS_TOKEN}
client_refresh_token: ${CLIENT_REFRESH_TOKEN}
jwt_technical_user: ${JWT_TECHNICAL_USER}

