spring:
  application:
    name: client-self-service
  cache:
    type: redis
    redis:
      time-to-live: 60000
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://case-lab-java-discovery-service:8761
client_access_token: ${CLIENT_ACCESS_TOKEN}
client_refresh_token: ${CLIENT_REFRESH_TOKEN}
jwt_technical_user: ${JWT_TECHNICAL_USER}

