spring:
  application:
    name: client-self-service
  cache:
    redis:
      time-to-live: 60000
server:
  port: 8081
redis_host_name: redis
redis_password: test
redis_username: ${REDIS_USERNAME}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
client_access_token: ${CLIENT_ACCESS_TOKEN}
client_refresh_token: ${CLIENT_REFRESH_TOKEN}
jwt_technical_user: ${JWT_TECHNICAL_USER}

