spring:
  datasource:
    url: jdbc:postgresql://178.21.8.3:5432/
    name: ${{ secrets.POSTGRES_DB }}
    username: ${{ secrets.POSTGRES_USER }}
    password: ${{ secrets.POSTGRES_PASSWORD }}
  jpa:
    show-sql: false

access_token: ${{ secrets.ACCESS_TOKEN }}
refresh_token: ${{ secrets.REFRESH_TOKEN }}