spring:
  datasource:
    url: jdbc:postgresql:
    driver-class-name: org.postgresql.Driver
    username: 
    password: 
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
access_token:
refresh_token:
