server:
  port: 8080

spring:
  profiles:
    active: @profileActive@
  application:
    name: CaseLabJavaCrm
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

access_token: ${ACCESS_TOKEN}
refresh_token: ${REFRESH_TOKEN}

