spring:
  datasource:
    url: jdbc:postgresql://case-lab-db:5432/
    name: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true

kafka:
  url: ${BOOTSTRAP_SERVERS_CONFIG}

minio:
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}
  url: ${MINIO_URL}