spring:
  datasource:
    url: jdbc:postgresql://89.223.124.249:5432/caselab
    driver-class-name: org.postgresql.Driver
    username: case_lab_admin
    password: 8b,4fA]]’o
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
access_token: 95Pol70Mvwlqp44evymFD6hACz1Prsko+0y4+cqN4obK2/jnWTJD/pmgUl99mINHWfvSGrJqZBZbT+DEd0vmaA==
refresh_token: W3H2tdRbjlBy2FsdJF28bxjgJyiSmVM+jcM7+CByFIszEqcYLemnMVoUJTNDFI2lFMt9ROoCUL8eVFPMqvfZuQ==