spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_IP}:5432/${CLIENT_SERVICE_DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
server:
  port: 8082