spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_IP}:5432/client-service-dev
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://case-lab-java-discovery-service:8761