server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/${PAYMENT_DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
