server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${ACQUIRING_DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect