server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${ACQUIRING_DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: ./db/changelog/db.changelog-master.xml
  mail:
    port: ${MAIL_PORT}
    default-encoding: utf-8
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable:
              true