server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:5432/${ACQUIRING_DB_NAME}
    username: ${ACQUIRING_POSTGRES_USER}
    password: ${ACQUIRING_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: ./db/changelog/db.changelog-master.xml
  mail:
    port: ${MAIL_PORT}
    default-encoding: utf-8
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable:
              true
  application:
    name: acquiring-service
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/