spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:5432/${CRM_DB_NAME}
    username: ${CRM_POSTGRES_USER}
    password: ${CRM_POSTGRES_PASSWORD}
  jpa:
    show-sql: true

minio:
  access-key: root12345
  secret-key: root12345
  url: http://localhost:9000