spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:5432/${CRM_DB_NAME}
    username: ${CRM_POSTGRES_USER}
    password: ${CRM_POSTGRES_PASSWORD}
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
minio:
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}
  url: ${MINIO_URL}
