spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:5432/${CRM_DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
minio:
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}
  url: ${MINIO_URL}
