spring:
  datasource:
    url: jdbc:postgresql://45.130.43.231:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true

minio:
  access-key: root12345
  secret-key: root12345
  url: http://localhost:9000